# Tell Railway to use both Python and Node.js
[phases.setup]
nixPkgs = ["python39", "nodejs-18_x", "libsndfile", "ffmpeg"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "cd vibrato-viewer && npm install && npm run build && cd .."
]

[start]
cmd = "uvicorn backend:app --host 0.0.0.0 --port $PORT"

